@startuml AlarmClockStateChart
skinparam monochrome true
skinparam state {
    FontName Helvetica
    FontSize 14
}

[*] --> Uninitialized

state Uninitialized {
    SetHour --> SetMinute : PushButton pressed
    SetHour --> SetHour : RotaryButton pressed/++Hour
    SetMinute --> SetMinute: RotaryButton pressed/++Minute
    [*] --> SetHour
}
    Uninitialized --> NormalOperation : PushButton pressed

    NormalOperation --> NormalOperation : RotaryButton pressed/AlarmEnabled or disabled
    NormalOperation --> SetAlarmTime : PushButton pressed
    NormalOperation: Toggle green LED
    
    state SetAlarmTime {
        [*] --> SetAlarmHour
        SetAlarmHour --> SetAlarmMinute : PushButton pressed
        SetAlarmHour --> SetAlarmHour : RotaryButton pressed/++Hour
        SetAlarmMinute --> NormalOperation : PushButton pressed
        SetAlarmMinute --> SetAlarmMinute : RotaryButton pressed/++Minute
    }
    
    NormalOperation --> AlarmTriggered : Alarm enabled AND time matches
    AlarmTriggered : Toggle red LED
    AlarmTriggered --> NormalOperation : Any button pressed or 5s timeout


@enduml